# Generated by Django 2.2.1 on 2019-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adebayo_osinulu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.DecimalField(decimal_places=0, max_digits=25),
        ),
    ]
